title: Jun's Blog
theme: jekyll-theme-minimal
markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Add navigation
header_pages:
  - index.md
  - tutorial.md
  - data_acq.md
  - about.md
